import type { Employee } from "../backend.d";

const STORAGE_KEY = "salary_mgr_employees_data";

// Serializable format for localStorage (bigint as string)
type StoredEmployee = Omit<
  Employee,
  "basicSalary" | "allowances" | "joiningDate"
> & {
  basicSalary: string;
  allowances: string;
  joiningDate: string;
};

function toStored(e: Employee): StoredEmployee {
  return {
    ...e,
    basicSalary: e.basicSalary.toString(),
    allowances: e.allowances.toString(),
    joiningDate: e.joiningDate.toString(),
  };
}

function fromStored(s: StoredEmployee): Employee {
  return {
    ...s,
    basicSalary: BigInt(s.basicSalary),
    allowances: BigInt(s.allowances),
    joiningDate: BigInt(s.joiningDate),
  };
}

const DEFAULT_JOINING = (BigInt(Date.now()) * 1_000_000n).toString();

const SEED_EMPLOYEES: StoredEmployee[] = [
  {
    id: "298",
    name: "Ajay Kumar Tiwari",
    designation: "Section Officer",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "418",
    name: "Amit Singh",
    designation: "Section Officer",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "438",
    name: "Arvind Kumar Sahu",
    designation: "Assistant",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "419",
    name: "Kuljeet Kaur",
    designation: "Section Officer",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "285",
    name: "Mousami Dhar",
    designation: "Section Officer",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3359",
    name: "Raj Bihari Singh",
    designation: "Administrator",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "433",
    name: "Sachin Kumar Patel",
    designation: "Accounts Assistant",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3418",
    name: "Sandeep Bannait",
    designation: "UDC",
    department: "",
    institute: "Bhel Shiksha Mandal",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "283",
    name: "Aachal Chavhan",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "160",
    name: "Afshan Parveen",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "248",
    name: "Aisha Khan",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "202",
    name: "Amreen Khan",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "261",
    name: "Amrita Malviya",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "326",
    name: "Amrita Nema",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3333",
    name: "Anju Saxena",
    designation: "Senior Teacher",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "331",
    name: "Anjula Gupta",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "376",
    name: "Archana Singh",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3354",
    name: "Ashok Kumar Ahirwar",
    designation: "Peon",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "204",
    name: "Balasubramani Vibha",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3346",
    name: "Daisamma Jose",
    designation: "Assistant Librarian",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "206",
    name: "Divya Malvi",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "252",
    name: "Jyoti Parmar",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "401",
    name: "Kartika Tomar",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "281",
    name: "Kavita Patil",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "429",
    name: "Kriti Raj",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "360",
    name: "Kshama Meena",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3347",
    name: "M P Anil",
    designation: "Senior PTI",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "311",
    name: "Madhavi Kanchan",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "425",
    name: "Manisha Jaiswar",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "412",
    name: "Manisha Kumari",
    designation: "PGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "216",
    name: "Meera Singh",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3380",
    name: "Mita B Jain",
    designation: "Senior Teacher",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "374",
    name: "Monika Jhariya",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "259",
    name: "Munazza Khan",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "198",
    name: "Neeta Rao",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "90",
    name: "Neha Kauser",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "249",
    name: "Neha Tiwari",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "260",
    name: "Nidhi Mathur",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "435",
    name: "Pinki Kumari",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "250",
    name: "Poonam Neelkanth",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "354",
    name: "Prashansa Soni",
    designation: "LDC",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "144",
    name: "Premlata Raghuwanshi",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "222",
    name: "Priyanka Singh Chouhan",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "276",
    name: "Puja Dhawan",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "303",
    name: "Puja Kumari",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "3376",
    name: "Ramesh Kumar Chouhan",
    designation: "Assistant",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Permanent",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "337",
    name: "Rashmi Saxena",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "403",
    name: "Ravi Kumar Gautam",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "244",
    name: "Rekha Gabriel",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "158",
    name: "Renu Verma",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "386",
    name: "Rishabh Sharma",
    designation: "PTI",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "372",
    name: "Ritika Sharma",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "416",
    name: "Ruchi Ghore Shilpi",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "290",
    name: "Ruchi Tiwari",
    designation: "Section Officer",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "373",
    name: "Rupali Saha Bose",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "375",
    name: "Sadiya Saeed",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "279",
    name: "Sandhya Patel",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "102",
    name: "Sapna Sapra",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "245",
    name: "Sarita Yadav",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "436",
    name: "Savita Dubey",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "203",
    name: "Seema Swarnkar",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "428",
    name: "Shaher Bano",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "378",
    name: "Shahiya Parveen",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "218",
    name: "Shaikh Mariyam Jamila",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "431",
    name: "Shashi Dsouza",
    designation: "PGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "251",
    name: "Shehla Parveen",
    designation: "TGT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "211",
    name: "Teena Bhojwani",
    designation: "PRT",
    department: "",
    institute: "Jawharlal Nehru School (PW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
  {
    id: "400",
    name: "Aayasha Khan",
    designation: "PGT",
    department: "",
    institute: "Jawharlal Nehru School (SW)",
    employeeType: "Temporary",
    employeeStatus: "Active",
    basicSalary: "0",
    allowances: "0",
    joiningDate: DEFAULT_JOINING,
    dob: "",
    religion: "",
    gender: "",
    category: "",
    phone: "",
    emailId: "",
    address: "",
    bhelQuarter: false,
    bankName: "",
    bankAccount: "",
    ifscCode: "",
    pfNumber: "",
    esiNumber: "",
    aadhaarNo: "",
    panNo: "",
    uanNo: "",
    licNo: "",
    profilePic: "",
  },
];

function isSeedLoaded(): boolean {
  return localStorage.getItem(`${STORAGE_KEY}_seeded`) === "1";
}

function loadSeed() {
  if (isSeedLoaded()) return;
  const existing = getRawEmployees();
  const existingIds = new Set(existing.map((e) => e.id));
  const toAdd = SEED_EMPLOYEES.filter((e) => !existingIds.has(e.id));
  if (toAdd.length > 0) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify([...existing, ...toAdd]));
  }
  localStorage.setItem(`${STORAGE_KEY}_seeded`, "1");
}

function getRawEmployees(): StoredEmployee[] {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "[]");
  } catch {
    return [];
  }
}

export function getAllEmployees(): Employee[] {
  loadSeed();
  return getRawEmployees().map(fromStored);
}

export function getEmployee(id: string): Employee | null {
  loadSeed();
  const found = getRawEmployees().find((e) => e.id === id);
  return found ? fromStored(found) : null;
}

export function saveEmployee(employee: Employee): void {
  loadSeed();
  const existing = getRawEmployees().filter((e) => e.id !== employee.id);
  localStorage.setItem(
    STORAGE_KEY,
    JSON.stringify([...existing, toStored(employee)]),
  );
}

export function deleteEmployee(id: string): void {
  const existing = getRawEmployees().filter((e) => e.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(existing));
}
