/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'bankAccount' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'joiningDate' : Time,
  'pfNumber' : IDL.Text,
  'allowances' : IDL.Nat,
  'department' : IDL.Text,
  'esiNumber' : IDL.Text,
  'basicSalary' : IDL.Nat,
});
export const SalaryRecord = IDL.Record({
  'da' : IDL.Nat,
  'hra' : IDL.Nat,
  'tds' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'netSalary' : IDL.Nat,
  'isFinalized' : IDL.Bool,
  'employeeId' : IDL.Text,
  'esiDeduction' : IDL.Nat,
  'basic' : IDL.Nat,
  'allowances' : IDL.Nat,
  'pfDeduction' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const AttendanceRecord = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'daysAbsent' : IDL.Nat,
  'employeeId' : IDL.Text,
  'leaves' : IDL.Nat,
  'daysPresent' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'addSalaryRecord' : IDL.Func([SalaryRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getMonthlyPayBill' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(SalaryRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttendance' : IDL.Func([AttendanceRecord], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'bankAccount' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'joiningDate' : Time,
    'pfNumber' : IDL.Text,
    'allowances' : IDL.Nat,
    'department' : IDL.Text,
    'esiNumber' : IDL.Text,
    'basicSalary' : IDL.Nat,
  });
  const SalaryRecord = IDL.Record({
    'da' : IDL.Nat,
    'hra' : IDL.Nat,
    'tds' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'netSalary' : IDL.Nat,
    'isFinalized' : IDL.Bool,
    'employeeId' : IDL.Text,
    'esiDeduction' : IDL.Nat,
    'basic' : IDL.Nat,
    'allowances' : IDL.Nat,
    'pfDeduction' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const AttendanceRecord = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'daysAbsent' : IDL.Nat,
    'employeeId' : IDL.Text,
    'leaves' : IDL.Nat,
    'daysPresent' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'addSalaryRecord' : IDL.Func([SalaryRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getMonthlyPayBill' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttendance' : IDL.Func([AttendanceRecord], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };